In [57]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = ""

import scipy
import numpy as np

from nodepy import runge_kutta_method as rk

In [63]:
import numpy as np
from scipy.special import roots_legendre

# Number of stages
s = 3

# Generate the roots and weights for the Gauss-Legendre quadrature rule
x, w = roots_legendre(s)

# Generate the A matrix
A = np.zeros((s, s))
for i in range(s):
    for j in range(s):
        if j == i:
            A[i, j] = x[i] * (1 - x[i])
        else:
            A[i, j] = (x[i] + x[j]) / ((x[i] - x[j]) * (1 - x[i] * x[j]))

# Generate the B and C vectors
B = np.array([(w[i] / 2) for i in range(s)])
C = np.array([((1 + x[i]) / 2) for i in range(s)])

# Normalize the B and C vectors
B /= np.sum(B)
C /= np.sum(C)

# Print the Butcher table
print("A:")
print(A)
print("B:")
print(B)
print("C:")
print(C)

A:
[[-1.37459667  1.         -0.        ]
 [-1.          0.         -1.        ]
 [ 0.          1.          0.17459667]]
B:
[0.27777778 0.44444444 0.27777778]
C:
[0.07513444 0.33333333 0.59153222]
